services:
  dfki_quad:
    image: dfki_quad:latest
    container_name: dfki_quad
    labels:
      - dfki_quad
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    working_dir: /root/ros2_ws
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ws/src:/root/ros2_ws/src
      - ./ws/build:/root/ros2_ws/build
      - ./ws/install:/root/ros2_ws/install
      - ./ws/log:/root/ros2_ws/log
      - ./ws/data:/root/ros2_ws/data
      - /home/${USER}/.ros_docker_bash_history:/root/.bash_history
      - /dev/input:/dev/input
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
